---
galaxy_info:
  author: Kazimierz Biskup
  description: Manages local users, groups, SSH access, sudo rules, and the root account.
  license: MIT
  min_ansible_version: "2.18"

  platforms:
    - name: EL
      versions:
        - "10"
    - name: Ubuntu
      versions:
        - noble
        - resolute
    - name: Debian
      versions:
        - trixie

dependencies: []
